name: FancyTab
author: Codebucket
version: 2.2 Release
main: de.codebucket.fancytab.FancyTab
website: http://www.codebucket.de
commands:
     tabreload:
          description: Reload Tablist (Plugin)
          usage: /<command>